INSERT INTO `learnlanguages_thanks`(`language`, `language_code`, `phrase`) VALUES
 ('Russian','rus','БЛАГОДАРЮ ПОЧТАЛЬОНА')
,('Ukrainian','ua','ДЯКУЮ ЛИСТОНОШI')
,('Belarusian','be','ДЗЯКУЮ ПАШТАЛЬЁНА')
,('Bulgarian','bg','БЛАГОДАРЯ ТИ ПОЩАЛЬОН')
,('Chinese','zh','感謝郵遞員')
,('Czech','cz','DÍKY POŠTOVNÍM PRACOVNÍKŮM')
,('Dutch','nl','DANKJEWEL POSTBODE')
,('English','eng','THANKS TO THE POSTAL WORKERS')
,('Finnish','fin','KIITOS POSTIMIEHELLE')
,('French','fra','JE REMERCIE LE FACTEUR')
,('German','deu','ICH DANKE DEN POSTANGESTELLTEN')
,('Greek','elo','ΧΆΡΗ ΣΤΟΝ ΤΑΧΥΔΡΌΜΟ')
,('Hindi','hin','धन्यवाद डाकिया')
,('Hungarian','hu','KÖSZÖNÖM A POSTÁSNAK')
,('Indonesian','id','TERIMA KASIH TUKANG POS')
,('Irish','ga','BUÍOCHAS LE FEAR AN PHOIST')
,('Italian','ita','GRAZIE POSTINO')
,('Japanese','jpn','郵便屋さんありがとう')
,('Korean','kor','우편 배달부에게 고마워')
,('Macedonian','mk','БЛАГОДАРАМ ПОШТАРОТ')
,('Malayalam','ml','TERIMA KASIH ENCIK POSMEN')
,('Philippine','phi','SALAMAT POSTMAN')
,('Polish','pol','DZIĘKUJĘ LISTONOSZOWI')
,('Portuguese','por','MUITO OBRIGADO, CARTEIRO')
,('Serbian','srp','ШВАЛА ПОШТАРУ')
,('Spanish','spa','GRACIAS CARTERO')
,('Swedish','swe','TACK BREVBÄRARE')
,('Turkish','tur','POSTAMI İLETTIĞİN İÇİN TEŞEKKÜR EDERİM POSTACI')
,('Uzbek','uzb','RAHMAT POCHTALON')
,('Slovenian','slv','HVALA, DRAGI POŠTAR')
,('Romanian','ron','MULȚUMESC POȘTAȘULUI')
,('Slovak','slk','ĎAKUJEM POŠTÁROVI')
,('Swahili','swa','ASANTE POSTMAN')
;